// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukYV3t3G-K9nC2Ry0Cg5FgeCaLx2LxD0',
    appId: '1:775981254090:web:1fac6f3a16241e2e1b7b33',
    messagingSenderId: '775981254090',
    projectId: 'biketracker-5d749',
    authDomain: 'biketracker-5d749.firebaseapp.com',
    databaseURL: 'https://biketracker-5d749-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketracker-5d749.firebasestorage.app',
    measurementId: 'G-8KQRH8LYC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61qZ3B4-uZFsKh5rOxf0AcgFXOACVEHU',
    appId: '1:775981254090:android:25d876a07b929ef51b7b33',
    messagingSenderId: '775981254090',
    projectId: 'biketracker-5d749',
    databaseURL: 'https://biketracker-5d749-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketracker-5d749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm7SxN6JIWxZdsfthElfXr7iCtM9YA2GY',
    appId: '1:775981254090:ios:a4c48a6f40290c591b7b33',
    messagingSenderId: '775981254090',
    projectId: 'biketracker-5d749',
    databaseURL: 'https://biketracker-5d749-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketracker-5d749.firebasestorage.app',
    iosBundleId: 'com.example.gppFitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm7SxN6JIWxZdsfthElfXr7iCtM9YA2GY',
    appId: '1:775981254090:ios:a4c48a6f40290c591b7b33',
    messagingSenderId: '775981254090',
    projectId: 'biketracker-5d749',
    databaseURL: 'https://biketracker-5d749-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketracker-5d749.firebasestorage.app',
    iosBundleId: 'com.example.gppFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCukYV3t3G-K9nC2Ry0Cg5FgeCaLx2LxD0',
    appId: '1:775981254090:web:522ab6ace7a94ed01b7b33',
    messagingSenderId: '775981254090',
    projectId: 'biketracker-5d749',
    authDomain: 'biketracker-5d749.firebaseapp.com',
    databaseURL: 'https://biketracker-5d749-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'biketracker-5d749.firebasestorage.app',
    measurementId: 'G-YSF3WZ94SX',
  );

}